name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test --coverage
    - name: Upload coverage to Codecov
      if: success()
      run: curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
